show the link

###  Step 1 — Importing Required Libraries
This step loads essential Python libraries for data handling, warnings suppression, and PCA implementation.

```python
import pandas as pd
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")

Reference: 
1. https://www.youtube.com/watch?v=XO0US1aTA50
2. https://www.youtube.com/watch?v=QdBy02ExhGI

In [112]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import warnings

warnings.filterwarnings("ignore")

# Load Dataset
df = pd.read_csv("../lo1_lo2_lo3_supervised_learning/dataset/Cleaned_graduation_dataset.csv")
df.head()


,avg_score,class_label,Math,Physics,Chemistry,Programming,Statistics,Machine_Learning,Database,Communication,Ethics,Final_Project,Civil Engineering,Computer Science,Mechanical Engineering,Public Health
0,56.43,2,63.7,51.2,57.8,51.4,64.4,66.7,50.3,51.6,64.7,52.8,False,False,False,True
1,69.67,3,73.9,63.1,73.8,77.1,65.0,69.8,65.3,62.4,69.9,76.3,False,True,False,False
2,88.43,0,92.9,92.5,71.7,64.3,98.7,87.9,64.5,79.5,92.9,90.0,False,False,False,False
3,64.39,3,69.4,72.4,63.5,61.9,64.4,64.8,69.3,73.4,63.7,60.7,False,False,True,False
4,69.48,3,70.6,60.4,75.6,71.3,69.1,63.4,64.5,70.0,64.7,71.1,True,False,False,False


###  Step 2 — Clean your dataset once not cleaned and apply all preprocessing steps


In [113]:
df.shape

(9999, 16)

###  Step 2 — Splitting Features and Target Variable
In this step, we separate the dataset into:
- **`X`**: The feature matrix (all independent variables used for PCA and model training).  
- **`y`**: The target vector (dependent variable or class label to be predicted).  

We drop the `"class_label"` column from `df` to form `X`, while storing it separately as `y`.


In [114]:
X = df.drop("class_label", axis=1)
y = df['class_label']

###  Step 3 — Standardizing the Data
PCA is sensitive to the scale of data.  
In this step, we use **`StandardScaler`** to normalize all features so that each has:
- Mean = 0  
- Standard deviation = 1  

This ensures that features with larger scales don’t dominate the PCA results.


In [115]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-0.92850923, -0.25343405, -1.25704637, ..., -0.46775604,
        -0.4778895 ,  2.13931931],
       [ 0.25106937,  0.57080384, -0.30172658, ...,  2.13786659,
        -0.4778895 , -0.4674384 ],
       [ 1.92243602,  2.10614892,  2.05847524, ..., -0.46775604,
        -0.4778895 , -0.4674384 ],
       ...,
       [-0.86525388, -0.65747223, -0.29369869, ...,  2.13786659,
        -0.4778895 , -0.4674384 ],
       [ 1.07695257,  1.90412983,  0.43683997, ...,  2.13786659,
        -0.4778895 , -0.4674384 ],
       [-0.54630438, -0.32616092,  0.09966828, ..., -0.46775604,
        -0.4778895 , -0.4674384 ]])

###  Step 4 — Splitting Dataset into Training and Testing Sets
We divide our scaled dataset into:
- **Training set (80%)** — used to train the model  
- **Testing set (20%)** — used to evaluate model performance  

We use `random_state=30` to ensure reproducibility (same random split every time).


In [116]:
# DATASET SPLIT

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=30)


###  Step 5 — Model Training using Logistic Regression
Here, we use **Logistic Regression**, a supervised classification algorithm.  
- The model learns the relationship between features (`X_train`) and target labels (`y_train`).  
- The `.score()` method calculates accuracy on the **test set** to evaluate model performance.


In [117]:
# MODEL Training

model_before_pca = LogisticRegression()
model_before_pca.fit(X_train, y_train)
model_before_pca.score(X_test, y_test)


0.967

###  Step 6 — Applying PCA (Principal Component Analysis)
In this step, we perform **dimensionality reduction** using PCA.  
- `PCA(0.95)` means the algorithm will automatically choose the minimum number of components that explain **95% of the total variance** in the data.  
- This helps simplify the dataset while preserving most of the important information.  

We then transform the dataset `X` into the new reduced-dimensional space and check the resulting shape of `X_pca`.


# Use PCA to reduce dimensions

In [118]:
# Make transformation
pca = PCA(0.95)
X_pca = pca.fit_transform(X)
X_pca.shape

(9999, 9)

###  Step 7 — Checking Explained Variance Ratio
After performing PCA, it’s important to understand how much **variance (information)** each principal component captures.

- The attribute `pca.explained_variance_ratio_` shows the **percentage contribution** of each principal component to the total variance.
- The sum of these values equals approximately **0.95 (95%)**, since we set `PCA(0.95)`.
- Higher values for the first few components indicate they capture most of the important patterns in the dataset.


In [119]:
# Show important/remaining dimensions contribution (%) after reduction
pca.explained_variance_ratio_

array([0.74926404, 0.0284636 , 0.02795047, 0.02739685, 0.02694603,
       0.0266888 , 0.02659261, 0.02624809, 0.02611363])

###  Step 8 — Checking the Number of Principal Components Retained
The attribute `pca.n_components_` tells us **how many principal components** were automatically selected by PCA.

- Since we used `PCA(0.95)`, this value represents the **minimum number of components** needed to retain **95% of the dataset’s total variance**.
- This helps confirm how much dimensionality reduction was achieved compared to the original number of features.


In [120]:
# Total remaining Dimensions after reduction

pca.n_components_


np.int64(9)

###  Step 9 — Displaying the Transformed PCA Dataset
At this stage, we view the **transformed dataset** after applying PCA.

- `X_pca` contains the **new feature set** (principal components) that summarize the original features.
- Each column now represents a **principal component (PC1, PC2, PC3, ...)**, capturing key variance patterns.
- The number of columns equals the value shown earlier by `pca.n_components_`.


In [121]:

X_pca


array([[-31.53241741,  -1.79187927,  -0.34961855, ...,  15.03028633,
          5.16991838,   2.66041812],
       [  9.18933697,   4.43537322,  -4.27796023, ...,   3.934944  ,
          3.6988353 ,  -4.10963838],
       [ 56.58700278, -25.80027851,   0.75713768, ...,   7.68985764,
          2.7515727 ,  13.81775953],
       ...,
       [-32.30727186,  -8.57813862,  -5.31508803, ...,   2.82881755,
         -2.53050161,   2.85113234],
       [ 39.97424351,   3.02574131,  -0.0710721 , ...,   6.18892835,
         12.0394953 ,  -7.02558284],
       [-15.61213553,   0.47449731,   6.36067066, ...,   6.68100064,
         -2.25037419,   5.3234054 ]])

###  Step 10 — Training the Model After PCA Reduction
Now that the dataset has been reduced using PCA, we:
1. **Split** the PCA-transformed data (`X_pca`) into training and testing subsets (80%–20% ratio).
2. **Train** a Logistic Regression model using the lower-dimensional data.
3. **Evaluate** the model’s accuracy using the test set.

This allows us to compare the model’s performance **before and after PCA** to see whether dimensionality reduction improves efficiency or accuracy.


In [122]:
# DATASET SPLIT
X_train_pca_95, X_test_pca_95, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=30)

# MODEL Training After Applying PCA
model_pca_95 = LogisticRegression()
model_pca_95.fit(X_train_pca_95, y_train)
model_pca_95.score(X_test_pca_95, y_test)

0.967

###  Step 11 — Reducing Data to 2 Principal Components
In this step, we apply PCA again — this time explicitly setting `n_components=2`.

- This forces the PCA to extract only **two principal components** (PC1 and PC2).  
- These two components capture the **maximum possible variance** in just two dimensions.
- This is especially useful for **visualization**, as it allows us to plot the data in a **2D scatter plot** and observe class separation patterns.


In [123]:
pca_2 = PCA(n_components=2)
X_pca_2 = pca.fit_transform(X)
X_pca_2.shape



(9999, 9)

###  Step 12 — Model Training Using 2D PCA Features
After reducing the dataset to **2 principal components**, we:
1. **Split** the transformed dataset (`X_pca`) into training and testing sets (80% for training, 20% for testing).  
2. **Train** a Logistic Regression model using the 2D PCA-transformed data.  
3. **Evaluate** the model’s performance by computing accuracy on the test set.  

This step helps us assess how well a simple 2D PCA representation preserves class-discriminating information for classification tasks.


In [124]:
# DATASET SPLIT

X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca_2, y, test_size=0.2, random_state=30)


# MODEL Training After Applying PCA

model_2pca = LogisticRegression()
model_2pca.fit(X_train_pca, y_train)
model_2pca.score(X_test_pca, y_test)

0.967

##  Step 13 — Model Comparison, Selection, and Deployment

In this final stage, we:
1. **Compare model performances** — evaluate accuracy (or other metrics) of the Logistic Regression model:
   - **Before PCA** → trained on the full original feature set  
   - **After PCA** → trained on reduced-dimensional data  
2. **Select the best-performing model** — based on accuracy, simplicity, and computational efficiency.  
3. **Save the best model** using `joblib` or `pickle` for deployment and future predictions.  
   - Saving ensures we can easily load the model later without retraining.  


In [125]:
import joblib

#  Calculate model accuracies
acc_before_pca = model_before_pca.score(X_test, y_test)       # Original model
acc_pca_95 = model_pca_95.score(X_test_pca_95, y_test)        # PCA retaining 95% variance
acc_pca_2 = model_2pca.score(X_test_pca, y_test)              # PCA with 2 components

#  Display results
print("Model Performance Summary:")
print(f"1️ Accuracy before PCA:        {acc_before_pca:.4f}")
print(f"2️ Accuracy with PCA (0.95):   {acc_pca_95:.4f}")
print(f"3️ Accuracy with PCA (2 PCs):  {acc_pca_2:.4f}")

#  Select the best model
best_model = None
best_acc = max(acc_before_pca, acc_pca_95, acc_pca_2)

if best_acc == acc_before_pca:
    best_model = model_before_pca
    print("\n Original model (without PCA) selected as best model.")
elif best_acc == acc_pca_95:
    best_model = model_pca_95
    print("\n PCA-based model (95% variance) selected as best model.")
else:
    best_model = model_2pca
    print("\n PCA-based model (2 components) selected as best model.")

#  Save the best model for deployment
joblib.dump(best_model, "best_model.pkl")
print("\n Best model saved successfully as 'best_model.pkl'")


Model Performance Summary:
1️ Accuracy before PCA:        0.9670
2️ Accuracy with PCA (0.95):   0.9670
3️ Accuracy with PCA (2 PCs):  0.9670

 Original model (without PCA) selected as best model.

 Best model saved successfully as 'best_model.pkl'


###  Optional Next Steps:
- **Deployment:**  
  You can deploy the saved model using frameworks like **FastAPI**, **Flask**, or **Streamlit** for real-time predictions.  
- **Model Monitoring:**  
  Continuously track model performance and retrain if accuracy drops due to data drift or new patterns.
